"""Distributed NumPy/CuPy arrays over MPI, with halo exchange.

::

    import mpiarray as mpa

    a = mpa.array([1, 2, 3, 4])   # under mpiexec -n 2: [1, 2] on rank 0, [3, 4] on rank 1
    b = mpa.zeros((64, 48), halo=1, periodic=(True, False))
    total = (2 * a).sum()          # collective: the same value on every rank

The creation functions (`array`, `zeros`, `arange`, `fromfunction`, ...)
split the array along ``split`` (default: the first axis) over the ranks of
``comm`` (default: ``MPI.COMM_WORLD``). Without an MPI launcher, mpiarray runs
serially on maybempi's stand-in for mpi4py, as one rank holding everything.
Arrays come from cunumpy, so the same code runs on NumPy or CuPy; on the CuPy
backend call ``xp.mpi.mpi_is_cuda_aware(comm)`` or
``xp.mpi.set_mpi_cuda_aware(...)`` once at startup.
"""

from mpiarray._mpi import default_comm
from mpiarray.creation import (
    arange,
    array,
    asarray,
    empty,
    empty_like,
    from_local,
    fromfunction,
    full,
    full_like,
    linspace,
    ones,
    ones_like,
    zeros,
    zeros_like,
)
from mpiarray.distributed_array import DistributedArray, HaloUpdate
from mpiarray.io import load, load_hdf5, save, save_hdf5
from mpiarray.layout import Layout, block_numbering, chunk_bounds, process_grid

# petsc4py is imported only when a PETSc function is called
from mpiarray.petsc import copy_from_petsc, copy_to_petsc, from_petsc, petsc_numbering
from mpiarray.points import migrate
from mpiarray.ufuncs import (
    arccos,
    arccosh,
    arcsin,
    arcsinh,
    arctan,
    arctan2,
    arctanh,
    bitwise_and,
    bitwise_or,
    bitwise_xor,
    cbrt,
    ceil,
    conj,
    conjugate,
    copysign,
    cos,
    cosh,
    deg2rad,
    degrees,
    divmod,
    exp,
    exp2,
    expm1,
    float_power,
    floor,
    fmax,
    fmin,
    fmod,
    gcd,
    heaviside,
    hypot,
    invert,
    isfinite,
    isinf,
    isnan,
    lcm,
    left_shift,
    log,
    log1p,
    log2,
    log10,
    logaddexp,
    logaddexp2,
    logical_and,
    logical_not,
    logical_or,
    logical_xor,
    maximum,
    minimum,
    mod,
    nextafter,
    rad2deg,
    radians,
    reciprocal,
    remainder,
    right_shift,
    rint,
    sign,
    signbit,
    sin,
    sinh,
    spacing,
    sqrt,
    square,
    tan,
    tanh,
    trunc,
)

__version__ = "0.1.0"

__all__ = [
    "DistributedArray",
    "HaloUpdate",
    "Layout",
    "__version__",
    "arange",
    "arccos",
    "arccosh",
    "arcsin",
    "arcsinh",
    "arctan",
    "arctan2",
    "arctanh",
    "array",
    "asarray",
    "bitwise_and",
    "bitwise_or",
    "bitwise_xor",
    "block_numbering",
    "cbrt",
    "ceil",
    "chunk_bounds",
    "conj",
    "conjugate",
    "copy_from_petsc",
    "copy_to_petsc",
    "copysign",
    "cos",
    "cosh",
    "default_comm",
    "deg2rad",
    "degrees",
    "divmod",
    "empty",
    "empty_like",
    "exp",
    "exp2",
    "expm1",
    "float_power",
    "floor",
    "fmax",
    "fmin",
    "fmod",
    "from_local",
    "from_petsc",
    "fromfunction",
    "full",
    "full_like",
    "gcd",
    "heaviside",
    "hypot",
    "invert",
    "isfinite",
    "isinf",
    "isnan",
    "lcm",
    "left_shift",
    "linspace",
    "load",
    "load_hdf5",
    "log",
    "log1p",
    "log2",
    "log10",
    "logaddexp",
    "logaddexp2",
    "logical_and",
    "logical_not",
    "logical_or",
    "logical_xor",
    "maximum",
    "migrate",
    "minimum",
    "mod",
    "nextafter",
    "ones",
    "ones_like",
    "petsc_numbering",
    "process_grid",
    "rad2deg",
    "radians",
    "reciprocal",
    "remainder",
    "right_shift",
    "rint",
    "save",
    "save_hdf5",
    "sign",
    "signbit",
    "sin",
    "sinh",
    "spacing",
    "sqrt",
    "square",
    "tan",
    "tanh",
    "trunc",
    "zeros",
    "zeros_like",
]
